// inl4/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AuthService } from './auth.service';
import { BehaviorSubject, Subject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  user = {}
  invalid;
  
  constructor(private authService: AuthService) {}

  ngOnInit(){
    this.user = this.authService.user
    if (this.user === null){
      this.user ={name: ''}
    }
  }

  login(username, password) {
    const cred = {username, password};
    this.authService.login(cred)
      .subscribe(data => {
        console.log(data, "from login")
        this.user = data
        this.invalid = false;
      },
      err => {
        this.invalid = err;
      }
    )}

  logout() {
    this.authService.logout()
    this.user = {}
  }

  testApi() {
    this.authService.getResource('friends')
      .subscribe(data => console.log(data))
  }
}

<div class="container">
  
  <!-- Complete this markup for showing error upon unsuccessful login. -->
  <p *ngIf="invalid" class="error">Login credentials were incorrect!</p>

  <!-- Complete this markup for showing the status bar correctly, depending on whether or not the user is authenticated. -->
  <div class="status">
    <span>User ID: {{user.name}}</span>
    <button (click)="testApi()">Test API</button>
    <button (click)="logout()">Logout</button>
  </div>

  <!-- Add markup for showing the login form if the user is not authenticated. -->
  <form *ngIf="!user.name" class="form-group">
    <input type="text" class="form-control" #username>
    <input type="password" class="form-control" #password>
    <button class="btn btn-primary" (click)="login(username.value, password.value)">Login</button>
  </form>
</div>

// inl4/react/src/App.js
import React, { Component } from 'react';

import AuthService from './authService';
import Login from './Login';

class App extends Component {
    // get the initial state from AuthService. 
    state = AuthService.getAuthState();
    login = false;

    // ...

    login = (username, password) => {
        AuthService.login({username, password})
            .then(() => {
                this.setState(AuthService.getAuthState());
                this.login = false;
            })
    };

    logout = () => {
        AuthService.logout()
        this.setState(AuthService.getAuthState());
    };

    testApi() {
        AuthService.getResource('friends')
            .then(res => console.log(res))
            .catch(err => console.log(err))
    }

    // ...

    render() {
        // complete the JSX code below to show the proper markup depending on whether or not the user has been authenticated.
        return (
            <div className="container">

                <p className="error">Login credentials were incorrect!</p>
                
                <div className="status">
                    <span>User ID:</span>
                    <button onClick={this.testApi}>Test API</button>
                    <button onClick={this.logout}>Logout</button>
                </div>
                
                <Login onLogin={this.login} />

            </div>
        );
    }
}

export default App;
